-- ============================================================================
-- MOVILIDAD ELÉCTRICA LIGERA: EL ÁRBOL Y LAS PRIMERAS 50 (2026-08-25)
-- ============================================================================
-- Eugenio, en tres mensajes seguidos:
--   1. «recopilar las mejores publicaciones de cada tema y subtema […] enseñar
--      contenido relevante en forma de mapas, imágenes, vídeos, textos y
--      gráficas cada vez que alguien pulse en un tema concreto»;
--   2. «puedes añadir un breve comentario como "IA" de por qué es relevante»;
--   3. «de esas 50 publicaciones, puedes crear subtemas y ligarlos al nuevo
--      menú que está construyendo el Programador 2».
--
-- ── EL ÁRBOL SALE DEL CONTENIDO, NO AL REVÉS ───────────────────────────────
-- Los 31 subtemas de aquí abajo no están inventados de antemano: cada uno
-- existe porque al menos una de las 50 piezas cae dentro. Un árbol escrito
-- primero y llenado después se queda con ramas vacías, y una rama vacía en un
-- menú es peor que no tener la rama: promete algo que no está.
--
-- Lo que Eugenio pidió como ejemplo —«pedaleo sin cadena»— NO está creado, y
-- es a propósito: ninguna de las 50 lo toca. Está anotado abajo, en la lista de
-- huecos, que es la otra cosa que un árbol honesto tiene que saber decir.
--
-- Cuelga de O008 MOVILIDAD. El disparador `subtemas_heredan` de 0120 se encarga
-- de que los hijos hereden el objetivo, así que aquí sólo hace falta ponérselo
-- bien a la raíz.
--
-- Los identificadores son legibles (`ST_MEL_CARGA_FAM`) en vez del `ST_<azar>`
-- que genera la API, porque esto es una semilla que hay que poder leer, revisar
-- y volver a ejecutar. `ON CONFLICT DO NOTHING` en todo: pasarlo dos veces no
-- duplica nada.

-- ── EL ÁRBOL ────────────────────────────────────────────────────────────────
INSERT INTO subtemas (id, objetivo_id, padre_id, nombre, nombre_clave, creador_user_id, orden) VALUES
  ('ST_MEL', 'O008', NULL, 'Movilidad eléctrica ligera', 'movilidad electrica ligera', 'agente:prog8', 0),
  ('ST_MEL_BICI', 'O008', 'ST_MEL', 'Bicicleta eléctrica', 'bicicleta electrica', 'agente:prog8', 1),
  ('ST_MEL_BICI_LIGERA', 'O008', 'ST_MEL_BICI', 'Plegables y ligeras', 'plegables y ligeras', 'agente:prog8', 2),
  ('ST_MEL_CARGA', 'O008', 'ST_MEL', 'Bicicleta de carga', 'bicicleta de carga', 'agente:prog8', 3),
  ('ST_MEL_CARGA_FAM', 'O008', 'ST_MEL_CARGA', 'Carga familiar', 'carga familiar', 'agente:prog8', 4),
  ('ST_MEL_CARGA_REP', 'O008', 'ST_MEL_CARGA', 'Reparto urbano', 'reparto urbano', 'agente:prog8', 5),
  ('ST_MEL_VMP', 'O008', 'ST_MEL', 'Patinete eléctrico (VMP)', 'patinete electrico vmp', 'agente:prog8', 6),
  ('ST_MEL_VMP_COMP', 'O008', 'ST_MEL_VMP', 'Patinete compartido', 'patinete compartido', 'agente:prog8', 7),
  ('ST_MEL_CICLO', 'O008', 'ST_MEL', 'Ciclomotor y moto eléctrica ligera', 'ciclomotor y moto electrica ligera', 'agente:prog8', 8),
  ('ST_MEL_TRICI', 'O008', 'ST_MEL', 'Triciclo eléctrico', 'triciclo electrico', 'agente:prog8', 9),
  ('ST_MEL_BAT', 'O008', 'ST_MEL', 'Baterías y seguridad eléctrica', 'baterias y seguridad electrica', 'agente:prog8', 10),
  ('ST_MEL_BAT_FUEGO', 'O008', 'ST_MEL_BAT', 'Fuga térmica e incendios', 'fuga termica e incendios', 'agente:prog8', 11),
  ('ST_MEL_BAT_CERT', 'O008', 'ST_MEL_BAT', 'Certificación de batería', 'certificacion de bateria', 'agente:prog8', 12),
  ('ST_MEL_BAT_SOLIDO', 'O008', 'ST_MEL_BAT', 'Estado semisólido y sólido', 'estado semisolido y solido', 'agente:prog8', 13),
  ('ST_MEL_NORMA', 'O008', 'ST_MEL', 'Normativa y homologación', 'normativa y homologacion', 'agente:prog8', 14),
  ('ST_MEL_NORMA_ES', 'O008', 'ST_MEL_NORMA', 'España: VMP y DGT', 'espana vmp y dgt', 'agente:prog8', 15),
  ('ST_MEL_NORMA_US', 'O008', 'ST_MEL_NORMA', 'Estados Unidos', 'estados unidos', 'agente:prog8', 16),
  ('ST_MEL_NORMA_INT', 'O008', 'ST_MEL_NORMA', 'Marco internacional', 'marco internacional', 'agente:prog8', 17),
  ('ST_MEL_SEG', 'O008', 'ST_MEL', 'Seguridad vial y siniestralidad', 'seguridad vial y siniestralidad', 'agente:prog8', 18),
  ('ST_MEL_SUST', 'O008', 'ST_MEL', 'Sustitución de coche y emisiones', 'sustitucion de coche y emisiones', 'agente:prog8', 19),
  ('ST_MEL_SUST_MODAL', 'O008', 'ST_MEL_SUST', 'Reparto modal', 'reparto modal', 'agente:prog8', 20),
  ('ST_MEL_SUST_SALUD', 'O008', 'ST_MEL_SUST', 'Salud y calidad del aire', 'salud y calidad del aire', 'agente:prog8', 21),
  ('ST_MEL_INFRA', 'O008', 'ST_MEL', 'Carril, aparcamiento e intercambio', 'carril aparcamiento e intercambio', 'agente:prog8', 22),
  ('ST_MEL_DATOS', 'O008', 'ST_MEL', 'Datos abiertos y estándares', 'datos abiertos y estandares', 'agente:prog8', 23),
  ('ST_MEL_DATOS_GBFS', 'O008', 'ST_MEL_DATOS', 'GBFS', 'gbfs', 'agente:prog8', 24),
  ('ST_MEL_DATOS_MDS', 'O008', 'ST_MEL_DATOS', 'MDS y regulación digital', 'mds y regulacion digital', 'agente:prog8', 25),
  ('ST_MEL_DATOS_PANEL', 'O008', 'ST_MEL_DATOS', 'Paneles municipales', 'paneles municipales', 'agente:prog8', 26),
  ('ST_MEL_MERCADO', 'O008', 'ST_MEL', 'Industria y mercado', 'industria y mercado', 'agente:prog8', 27),
  ('ST_MEL_MERCADO_CN', 'O008', 'ST_MEL_MERCADO', 'Fabricación en Asia', 'fabricacion en asia', 'agente:prog8', 28),
  ('ST_MEL_MERCADO_EU', 'O008', 'ST_MEL_MERCADO', 'Fabricación en Europa', 'fabricacion en europa', 'agente:prog8', 29),
  ('ST_MEL_MERCADO_CIF', 'O008', 'ST_MEL_MERCADO', 'Ventas y cifras', 'ventas y cifras', 'agente:prog8', 30)
ON CONFLICT (id) DO NOTHING;

-- ── LAS 50 PIEZAS ───────────────────────────────────────────────────────────
-- `calidad` la he puesto yo, de 0 a 100, y `calidad_por` dice por qué. NO es
-- popularidad: el 97 es un informe del ITF que habrán leído cuatro mil personas
-- y el 48 es una página de Statista que verán cien mil. Si esto se ordenara por
-- visitas, la portada del subtema sería la lista de lo más visto de YouTube,
-- que ya existe en otro sitio y no hace falta repetirla aquí.
--
-- Los 19 vídeos están comprobados uno a uno contra el oEmbed de YouTube (el
-- identificador existe y el título es el real, no el que yo recordara). Los 31
-- enlaces restantes, contra su servidor. Los seis marcados
-- `estado = 'bloquea_robots'` devuelven 403 a un programa y 200 a una persona:
-- están vivos, y son justamente los más serios de la lista.

INSERT INTO contenido_agregado (id, origen, formato, url, origen_id, titulo, fuente, idioma, publicado_el, nota_ia, nota_modelo, nota_el, calidad, calidad_por, estado, comprobado_el, puesto_por) VALUES
  ('AGR_MEL_001', 'youtube', 'video', 'https://www.youtube.com/watch?v=RIhbHqSXCQ0', 'RIhbHqSXCQ0',
   'I need a cargo e-bike. Here''s how I''m choosing the right one',
   'Shifter', 'en', '2026-07-09'::date,
   'El mejor punto de entrada al tema para alguien que no sabe nada: en vez de reseñar un modelo, enseña el árbol de decisiones —dos ruedas o tres, alargada o de caja, motor central o de buje— que es lo que de verdad hay que entender antes de mirar precios.',
   'claude-opus-5', now(), 88, 'Explica el árbol de decisión completo, no un modelo suelto.',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_002', 'youtube', 'video', 'https://www.youtube.com/watch?v=SBy4D8_vq6w', 'SBy4D8_vq6w',
   'I Commuted Two Different Ways. The Winner Isn''t What you Think',
   'Shifter', 'en', '2026-05-14'::date,
   'Compara el mismo trayecto en coche y en bici eléctrica midiendo puerta a puerta. Es el experimento casero que resuelve la objeción más común contra este tema, la de que «para ir a trabajar no vale».',
   'claude-opus-5', now(), 82, 'Mide puerta a puerta; responde a la objeción más común con datos propios.',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_003', 'youtube', 'video', 'https://www.youtube.com/watch?v=B93phHGSgYs', 'B93phHGSgYs',
   'Cities are spending millions on bike lanes that don''t work. Here''s why',
   'Shifter', 'en', '2026-06-25'::date,
   'Relevante aunque no hable de vehículos: el cuello de botella de la movilidad ligera no es la batería, es el carril. Explica por qué una red de carriles inconexos no cambia el reparto modal por mucho que se gaste.',
   'claude-opus-5', now(), 80, 'Nombra el cuello de botella real del tema, que no es el vehículo.',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_004', 'youtube', 'video', 'https://www.youtube.com/watch?v=D1wyWwbSpW0', 'D1wyWwbSpW0',
   'This e-bike is impractical, unruly and totally lovable',
   'Shifter', 'en', NULL,
   'El contrapunto honesto de la colección. Casi todo el material del tema vende utilidad y ahorro; este enseña el otro motivo real por el que la gente se compra una, que es que le apetece.',
   'claude-opus-5', now(), 64, 'Contrapeso al discurso de utilidad; cubre el motivo emocional de compra.',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_005', 'youtube', 'video', 'https://www.youtube.com/watch?v=zzV--VEqZtc', 'zzV--VEqZtc',
   'Why We Love Cargo Bikes',
   'Fully Charged Electric Bikes', 'en', '2026-08-16'::date,
   'La bici de carga es el punto donde este tema deja de ser un accesorio y empieza a sustituir al segundo coche de una familia. Este vídeo es el argumento en su forma más clara y reciente.',
   'claude-opus-5', now(), 78, 'La defensa más clara y reciente de la categoría que sustituye coches.',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_006', 'youtube', 'video', 'https://www.youtube.com/watch?v=gOhH11BnDR4', 'gOhH11BnDR4',
   'Why The Tern GSD Replaced The Car',
   'Fully Charged Electric Bikes', 'en', '2026-07-28'::date,
   'Un caso concreto de sustitución de coche, que es exactamente la variable de la que depende todo el beneficio ambiental del tema según la literatura recogida más abajo. Vale como la cara humana de esos estudios.',
   'claude-opus-5', now(), 79, 'Caso concreto de la variable de la que depende todo el beneficio ambiental.',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_007', 'youtube', 'video', 'https://www.youtube.com/watch?v=L1dKUMAmJaw', 'L1dKUMAmJaw',
   'Inside Riese & Müller''s Factory',
   'Fully Charged Electric Bikes', 'en', '2026-07-22'::date,
   'Casi no hay material que enseñe cómo se fabrica esto en Europa. Sirve de contrapeso al vídeo de las fábricas chinas: dos modelos industriales del mismo producto, vistos por dentro.',
   'claude-opus-5', now(), 76, 'Casi no hay material sobre fabricación europea de este producto.',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_008', 'youtube', 'video', 'https://www.youtube.com/watch?v=WtBJ6eUsqpU', 'WtBJ6eUsqpU',
   'EVERY New Riese & Müller for 2027!',
   'Fully Charged Electric Bikes', 'en', '2026-07-25'::date,
   'Foto del techo técnico del segmento premium europeo para el año que viene. Útil como referencia de hasta dónde llega hoy la tecnología, no como recomendación de compra.',
   'claude-opus-5', now(), 62, 'Referencia del techo técnico del segmento premium; caduca en un año.',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_009', 'youtube', 'video', 'https://www.youtube.com/watch?v=E-mfLNBsaPk', 'E-mfLNBsaPk',
   'The New Tern HSD S9i Is Here',
   'Fully Charged Electric Bikes', 'en', '2026-07-15'::date,
   'La categoría compacta —carga de verdad en el tamaño de una bici normal— es la que resuelve el problema del portal y el ascensor, que es lo que frena la adopción en ciudad densa española.',
   'claude-opus-5', now(), 70, 'La categoría compacta es la que resuelve el problema del portal español.',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_010', 'youtube', 'video', 'https://www.youtube.com/watch?v=GU5MlrZnmE8', 'GU5MlrZnmE8',
   'How A Cargo Bike Changed Sophia''s Daily Life',
   'Fully Charged Electric Bikes', 'en', '2026-08-12'::date,
   'Testimonio de uso cotidiano con niños. Aporta lo que ningún informe recoge: la logística familiar real, que es donde se decide si el cambio de modo aguanta más de un mes.',
   'claude-opus-5', now(), 72, 'Logística familiar real, que no recoge ningún informe.',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_011', 'youtube', 'video', 'https://www.youtube.com/watch?v=qRzEZJse090', 'qRzEZJse090',
   '5 Ways E-Bikes Are Changing In 2026',
   'EbikeSchool.com', 'en', '2026-01-24'::date,
   'El resumen anual más útil que hay en vídeo: qué cambia este año en baterías, motores, precios y regulación. Es la pieza que mantiene fresca la portada del subtema.',
   'claude-opus-5', now(), 84, 'El resumen anual del subtema entero; es la pieza de portada.',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_012', 'youtube', 'video', 'https://www.youtube.com/watch?v=jOqkaBnm8Wk', 'jOqkaBnm8Wk',
   'World''s First Semi-Solid State Battery On Production E-Bike',
   'EbikeSchool.com', 'en', '2025-11-16'::date,
   'El frente técnico del tema es la batería, y esto es el primer semisólido montado en un producto en venta, no en un laboratorio. Marca el punto exacto del estado del arte en almacenamiento ligero.',
   'claude-opus-5', now(), 86, 'Marca el punto exacto del estado del arte en almacenamiento ligero.',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_013', 'youtube', 'video', 'https://www.youtube.com/watch?v=h69Jj8rqjXA', 'h69Jj8rqjXA',
   'I went to 7 Chinese factories in 7 days to see the truth',
   'EbikeSchool.com', 'en', '2026-01-03'::date,
   'China concentra la fabricación de casi todo lo que se vende en este tema. Esto es reportaje de campo dentro de esas fábricas, algo que no aparece en ningún informe sectorial.',
   'claude-opus-5', now(), 85, 'Reportaje de campo donde se fabrica todo; no existe equivalente escrito.',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_014', 'youtube', 'video', 'https://www.youtube.com/watch?v=t0y_BhXtFKg', 't0y_BhXtFKg',
   'The ACTUAL Danger of E-Trikes',
   'EbikeSchool.com', 'en', '2025-12-02'::date,
   'El triciclo eléctrico se vende como la opción segura para gente mayor y tiene un problema de vuelco en curva que casi nadie explica. Es el vídeo que contradice al marketing del propio sector.',
   'claude-opus-5', now(), 81, 'Contradice al marketing del propio sector sobre un riesgo real.',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_015', 'youtube', 'video', 'https://www.youtube.com/watch?v=Q-SdDWhdsyM', 'Q-SdDWhdsyM',
   'Dahon K-Feather Lightest E-Bike EVER?!',
   'EbikeSchool.com', 'en', '2026-01-14'::date,
   'El peso es la frontera práctica del tema: si hay que subirla a un piso o meterla en un tren, todo lo demás da igual. Este modelo empuja ese límite y por eso importa más que su ficha técnica.',
   'claude-opus-5', now(), 68, 'El peso es la frontera práctica del tema en ciudad densa.',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_016', 'youtube', 'video', 'https://www.youtube.com/watch?v=Ip3Hq7zVSDA', 'Ip3Hq7zVSDA',
   'Low-Cost Electric VESPA?! Aventura X E-Scooter Testing!',
   'EbikeSchool.com', 'en', '2025-10-26'::date,
   'El ciclomotor eléctrico barato es el vehículo que más gente mueve en el mundo y el que menos aparece en la conversación europea. Vale por cubrir el borde del tema que suele quedarse fuera.',
   'claude-opus-5', now(), 66, 'Cubre el borde del tema que la conversación europea siempre deja fuera.',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_017', 'youtube', 'video', 'https://www.youtube.com/watch?v=ypUGjGWo_hg', 'ypUGjGWo_hg',
   'Electric cargo bikes changed my life',
   'The Verge', 'en', NULL,
   'Producción de medio grande sobre bici de carga: es la pieza que se le puede enseñar a alguien que todavía cree que esto es un juguete. Buena calidad de imagen y argumento centrado en sustituir coche.',
   'claude-opus-5', now(), 77, 'Producción de medio grande; es la pieza para convencer a un escéptico.',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_018', 'youtube', 'video', 'https://www.youtube.com/watch?v=LpR-H9u9sVE', 'LpR-H9u9sVE',
   'The ULTIMATE Urban Cargo Bike?',
   'Path Less Pedaled', 'en', NULL,
   'Análisis desde el ciclismo, no desde la tecnología: mira geometría, manejo con carga y comportamiento en ciudad, que es donde fallan la mayoría de las bicis de carga baratas.',
   'claude-opus-5', now(), 74, 'Mira geometría y manejo con carga, donde fallan las baratas.',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_019', 'youtube', 'video', 'https://www.youtube.com/watch?v=uV6AgluPvo8', 'uV6AgluPvo8',
   '¿Cómo inscribir tu VMP en la sede electrónica de la DGT?',
   'DGT', 'es', '2026-03-04'::date,
   'El único vídeo institucional español de la tanda, y el trámite que va a afectar a todo el que tenga un patinete cuando venza la moratoria en enero de 2027. Aquí es utilidad pura, no divulgación.',
   'claude-opus-5', now(), 83, 'Único vídeo institucional español; trámite obligatorio antes de enero de 2027.',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_020', 'web', 'texto', 'https://www.itf-oecd.org/safer-micromobility', NULL,
   'Safer Micromobility',
   'ITF / OCDE', 'en', '2024-01-01'::date,
   'La referencia central del tema en seguridad, y la que revisa en 2024 las conclusiones de 2020. Si esta página solo pudiera enlazar un documento, sería este.',
   'claude-opus-5', now(), 97, 'La referencia central del tema en seguridad. La pieza número uno de las 50.',
   'bloquea_robots', now(), 'agente:prog8'),
  ('AGR_MEL_021', 'web', 'texto', 'https://www.itf-oecd.org/safe-micromobility', NULL,
   'Safe Micromobility',
   'ITF / OCDE', 'en', '2020-01-01'::date,
   'El informe original que propuso clasificar estos vehículos por masa y velocidad en vez de por nombre comercial. Ese marco es el que hoy usan media docena de regulaciones nacionales, la española incluida.',
   'claude-opus-5', now(), 94, 'Propuso el marco de masa y velocidad que hoy usan media docena de leyes.',
   'bloquea_robots', now(), 'agente:prog8'),
  ('AGR_MEL_022', 'web', 'texto', 'https://www.itf-oecd.org/10-recommendations-safe-micromobility', NULL,
   '10 Recommendations for Safe Micromobility',
   'ITF / OCDE', 'en', '2020-01-01'::date,
   'La versión corta y accionable del informe anterior: diez medidas concretas de calzada, diseño de vehículo y normas. Es lo que se le puede pasar a un ayuntamiento sin pedirle que lea 100 páginas.',
   'claude-opus-5', now(), 90, 'La versión accionable para un ayuntamiento.',
   'bloquea_robots', now(), 'agente:prog8'),
  ('AGR_MEL_023', 'pdf', 'texto', 'https://www.itf-oecd.org/sites/default/files/safer-micrombility-technical-report.pdf', NULL,
   'Safer Micromobility: Technical Background Report',
   'ITF / OCDE', 'en', '2024-03-01'::date,
   'El anexo con los datos crudos y el método detrás de las conclusiones. Es la fuente a la que hay que ir cuando alguien discuta la cifra de riesgo comparado con la bicicleta.',
   'claude-opus-5', now(), 89, 'Los datos crudos y el método detrás de la cifra de riesgo comparado.',
   'bloquea_robots', now(), 'agente:prog8'),
  ('AGR_MEL_024', 'web', 'texto', 'https://etsc.eu/itf-report-recommends-action-on-safety-of-e-scooters/', NULL,
   'ITF report recommends action on safety of e-scooters',
   'ETSC', 'en', NULL,
   'Vía de entrada abierta al informe del ITF, desde el consejo europeo de seguridad vial. Sirve justamente porque el original bloquea el acceso automático.',
   'claude-opus-5', now(), 71, 'Puerta abierta a un informe que bloquea el acceso automático.',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_025', 'web', 'texto', 'https://www.intelligenttransport.com/transport-news/95957/itf-report-outlines-recommendations-for-safety-of-micromobility-services/', NULL,
   'ITF report outlines recommendations for safety of micromobility services',
   'Intelligent Transport', 'en', NULL,
   'Resumen periodístico del mismo informe, centrado en los servicios compartidos. Segunda puerta abierta a un documento que no se deja leer directamente.',
   'claude-opus-5', now(), 67, 'Segunda puerta abierta, centrada en los servicios compartidos.',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_026', 'web', 'texto', 'https://www.iea.org/reports/global-ev-outlook-2025/trends-in-other-light-duty-electric-vehicles', NULL,
   'Global EV Outlook 2025 — Trends in other light-duty electric vehicles',
   'IEA', 'en', '2025-05-01'::date,
   'De aquí salen las dos cifras que abren esta página. Es el capítulo que la prensa se salta cuando cubre el Global EV Outlook, y es justo el que trata este tema.',
   'claude-opus-5', now(), 96, 'El capítulo que trata este tema, y del que salen las dos cifras de cabecera.',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_027', 'web', 'texto', 'https://www.iea.org/reports/global-ev-outlook-2026/executive-summary', NULL,
   'Global EV Outlook 2026 — Resumen ejecutivo',
   'IEA', 'en', '2026-01-01'::date,
   'La edición más reciente, para contrastar si la tendencia de 2024 se sostiene. Conviene leerla junto a la de 2025 y no en su lugar: el detalle de dos y tres ruedas vive en el capítulo, no en el resumen.',
   'claude-opus-5', now(), 87, 'La edición más reciente, para contrastar la tendencia.',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_028', 'web', 'texto', 'https://www.dgt.es/muevete-con-seguridad/viaja-seguro/en-patinete/', NULL,
   'En patinete',
   'DGT', 'es', NULL,
   'La página oficial con las reglas que se aplican en España hoy: 25 km/h, 25 kg, dos frenos, casco, luces. Es la respuesta directa a la pregunta que más veces se hace sobre este subtema.',
   'claude-opus-5', now(), 92, 'Respuesta oficial a la pregunta que más veces se hace del subtema.',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_029', 'web', 'texto', 'https://www.dgt.es/comunicacion/noticias/vmp-nuevas-reglas-nueva-formacion/', NULL,
   'VMP: nuevas reglas, nueva formación',
   'DGT', 'es', NULL,
   'Explica el cambio de régimen —certificado de conformidad, Manual de Características, moratoria hasta enero de 2027— que deja fuera de la ley a buena parte de los patinetes que ya circulan.',
   'claude-opus-5', now(), 88, 'El cambio de régimen que deja fuera de la ley a muchos patinetes en circulación.',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_030', 'articulo', 'texto', 'https://www.tandfonline.com/doi/full/10.1080/01441647.2025.2474556', NULL,
   'E-bikes and travel behaviour change: systematic review of experimental studies with meta-analyses',
   'Transport Reviews', 'en', '2025-01-01'::date,
   'La pieza de mayor peso metodológico de la colección: revisión sistemática con metaanálisis, no una encuesta más. Su límite, que conviene decir, es que los diez estudios incluidos son todos del norte de Europa.',
   'claude-opus-5', now(), 95, 'Mayor peso metodológico de la colección; su límite geográfico está dicho.',
   'bloquea_robots', now(), 'agente:prog8'),
  ('AGR_MEL_031', 'articulo', 'texto', 'https://doi.org/10.1016/j.trip.2024.101074', NULL,
   'Potential of e-bikes to replace passenger car trips and reduce greenhouse gas emissions',
   'Transp. Research Interdisc. Perspectives', 'en', '2024-01-01'::date,
   'Cuantifica lo que el resto solo enuncia: cuántos viajes de coche puede absorber la bici eléctrica y cuánto CO₂ son. Enlazada por DOI porque es la única forma de que el enlace sobreviva a los cambios de la editorial.',
   'claude-opus-5', now(), 91, 'Pone número a lo que el resto enuncia. Enlazado por DOI, que no se rompe.',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_032', 'articulo', 'texto', 'https://www.sciencedirect.com/org/science/article/pii/S0144164722004330', NULL,
   'What travel modes do shared e-scooters displace? A review of recent research findings',
   'ScienceDirect', 'en', '2022-01-01'::date,
   'Responde a la objeción más seria contra el patinete compartido: que le quita viajes a caminar, no al coche. La respuesta resulta ser «depende de la distancia», y eso cambia cómo debería regularse.',
   'claude-opus-5', now(), 90, 'Responde a la objeción más seria contra el patinete compartido.',
   'bloquea_robots', now(), 'agente:prog8'),
  ('AGR_MEL_033', 'articulo', 'texto', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC12641026/', NULL,
   'Incorporating active commuting into daily life: e-bikes'' impact on health and urban air quality',
   'PMC · NIH', 'en', NULL,
   'Trae el ángulo de salud, que es el que más pesa en una decisión municipal y el que menos aparece en la conversación técnica. Texto completo abierto.',
   'claude-opus-5', now(), 86, 'El ángulo de salud, que es el que más pesa en una decisión municipal.',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_034', 'web', 'texto', 'https://ebikesafety.ulse.org/', NULL,
   'E-Bike & E-Scooter Safety Action Center',
   'UL Standards & Engagement', 'en', NULL,
   'El centro de referencia sobre incendios de batería en estos vehículos: datos de incidentes, normas y legislación modelo en un solo sitio. Es la fuente que hay detrás de casi todas las noticias de este asunto.',
   'claude-opus-5', now(), 93, 'La fuente detrás de casi todas las noticias de incendios de batería.',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_035', 'web', 'texto', 'https://www.ul.com/services/e-bikes-certificationevaluating-and-testing-ul-2849', NULL,
   'UL 2849 — certificación de sistemas eléctricos de bicicletas',
   'UL Solutions', 'en', NULL,
   'UL 2849, 2272 y 2271 son las tres normas que Nueva York convirtió en obligatorias y que el resto está copiando. Saber qué certifica cada una es lo que separa una batería segura de una barata.',
   'claude-opus-5', now(), 85, 'Las tres normas que Nueva York hizo obligatorias y el resto está copiando.',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_036', 'web', 'texto', 'https://www.federalregister.gov/documents/2026/06/24/2026-12749/safety-standard-for-lithium-ion-batteries-used-in-micromobility-products-and-electrical-systems-of', NULL,
   'Safety Standard for Lithium-Ion Batteries Used in Micromobility Products',
   'Federal Register', 'en', '2026-06-24'::date,
   'Norma federal estadounidense en tramitación, de junio de este año. Es el documento que marca que esto dejó de ser autorregulación del sector y pasó a ser ley.',
   'claude-opus-5', now(), 89, 'El documento que marca el paso de autorregulación a ley.',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_037', 'web', 'texto', 'https://ul.org/press-releases/ul-research-institutes-releases-new-report-examining-the-fire-safety-hazards-of-e-mobility-devices-on-passenger-railcars/', NULL,
   'Fire safety hazards of e-mobility devices on passenger railcars',
   'UL Research Institutes', 'en', NULL,
   'Ensayo de incendio en un vagón real, con medición de calor y gases. Es la prueba física detrás de la pregunta práctica de si se puede subir un patinete al tren, que en España sigue sin respuesta clara.',
   'claude-opus-5', now(), 84, 'Ensayo físico en un vagón real; responde a «¿puedo subirlo al tren?».',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_038', 'datos', 'grafica', 'https://www.iea.org/data-and-statistics/data-tools/global-ev-data-explorer', NULL,
   'Global EV Data Explorer',
   'IEA', 'en', NULL,
   'Serie histórica y proyección filtrable por país y por tipo de vehículo, incluidos los de dos y tres ruedas. Es la fuente de la que deberían salir las gráficas de este subtema en vez de dibujarlas a mano.',
   'claude-opus-5', now(), 94, 'Fuente actualizable: de aquí deberían salir las gráficas del subtema.',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_039', 'datos', 'mapa', 'https://public.ridereport.com/', NULL,
   'Global Micromobility Dashboard',
   'Ride Report', 'en', NULL,
   'Datos agregados y anónimos de patinete y bici compartida de decenas de ciudades, en abierto. Es lo más cerca que hay de un mapa mundial vivo de este tema.',
   'claude-opus-5', now(), 92, 'Lo más cerca que hay de un mapa mundial vivo del tema.',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_040', 'datos', 'mapa', 'https://public.ridereport.com/denver', NULL,
   'Denver — panel municipal de micromovilidad',
   'Ride Report', 'en', NULL,
   'El mismo panel bajado a una ciudad concreta: viajes, flota y zonas. Sirve de modelo de lo que una ciudad española podría publicar y hoy no publica.',
   'claude-opus-5', now(), 78, 'Modelo de lo que una ciudad española podría publicar y no publica.',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_041', 'web', 'mapa', 'https://gbfs.org/', NULL,
   'GBFS — General Bikeshare Feed Specification',
   'MobilityData', 'en', NULL,
   'El estándar abierto que hace que casi nueve de cada diez sistemas norteamericanos publiquen su estado en tiempo real. Es la pieza técnica que convierte este tema en mapa en vez de en folleto.',
   'claude-opus-5', now(), 90, 'La pieza técnica que convierte este tema en mapa en vez de en folleto.',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_042', 'web', 'mapa', 'https://github.com/openmobilityfoundation/mobility-data-specification', NULL,
   'Mobility Data Specification (MDS)',
   'Open Mobility Foundation', 'en', NULL,
   'El complemento regulador de GBFS: permite a una ciudad poner condiciones y geovallas, no solo mirar. Aquí es donde se decide quién manda en la calle, y por eso está en esta lista y no en una de informática.',
   'claude-opus-5', now(), 86, 'Donde se decide quién manda en la calle; por eso está aquí y no en informática.',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_043', 'web', 'mapa', 'https://developers.google.com/micromobility/guides', NULL,
   'Micromobility — guías para desarrolladores',
   'Google for Developers', 'en', NULL,
   'Cómo un sistema de bici o patinete compartido acaba apareciendo dentro de Google Maps. Es el camino práctico para que lo que se publique en la plataforma sea encontrable fuera de ella.',
   'claude-opus-5', now(), 73, 'El camino para que lo que se publique aquí sea encontrable fuera.',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_044', 'pdf', 'texto', 'https://nabsa.net/wp-content/uploads/2021/01/FINAL-Data-Good-Practices-for-Municipalities_-Understanding-the-General-Bikeshare-Feed-Specification-GBFS-1.pdf', NULL,
   'Data Good Practices for Municipalities: Understanding GBFS',
   'NABSA', 'en', '2021-01-01'::date,
   'La traducción de GBFS al idioma de un ayuntamiento: qué pedir en un pliego y qué hacer con lo que llegue. Es el documento que le falta a la mayoría de contratos municipales españoles.',
   'claude-opus-5', now(), 80, 'El documento que le falta a la mayoría de pliegos municipales españoles.',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_045', 'datos', 'grafica', 'https://www.seattle.gov/transportation/projects-and-programs/programs/new-mobility-program/scooter-bike-share-data', NULL,
   'Scooter and Bike Share — datos y condiciones de licencia',
   'Seattle DOT', 'en', NULL,
   'Un caso real de ciudad que obliga por licencia a publicar los datos en abierto. Vale como precedente citable cuando aquí se discuta si exigirlo o no.',
   'claude-opus-5', now(), 76, 'Precedente citable de ciudad que obliga por licencia a publicar datos.',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_046', 'web', 'texto', 'https://playbook.t4america.org/data/', NULL,
   'Shared Micromobility Playbook — Data',
   'Transportation for America', 'en', NULL,
   'Manual de gobierno del dato para servicios compartidos: qué recoger, cómo anonimizarlo y para qué usarlo. Cierra el hueco entre tener los datos y saber qué decidir con ellos.',
   'claude-opus-5', now(), 79, 'Cierra el hueco entre tener los datos y saber qué decidir con ellos.',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_047', 'web', 'grafica', 'https://www.conebi.eu/industry-market-reports/', NULL,
   'European Bicycle Industry & Market Profile',
   'CONEBI', 'en', '2025-07-01'::date,
   'La serie de ventas y producción europea de la que sale la cifra de 5,1 millones de bicicletas eléctricas. Aviso: el informe completo es de pago; en abierto están las notas de prensa con los agregados.',
   'claude-opus-5', now(), 83, 'La serie europea de ventas. Aviso: el informe completo es de pago.',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_048', 'articulo', 'texto', 'https://arxiv.org/pdf/2310.19036', NULL,
   'Mode substitution induced by electric mobility hubs: results from Amsterdam',
   'arXiv', 'en', '2023-10-01'::date,
   'Mide la sustitución de modos alrededor de un punto de intercambio eléctrico, no de un vehículo suelto. Es la escala a la que se planifica una ciudad, y está en abierto.',
   'claude-opus-5', now(), 75, 'La escala a la que se planifica una ciudad, y en abierto.',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_049', 'web', 'texto', 'https://www.ce.washington.edu/news/article/2023-12-15/electric-cargo-bikes-future', NULL,
   'Electric cargo bikes: the future',
   'Univ. of Washington CEE', 'en', '2023-12-15'::date,
   'Resumen académico divulgativo sobre reparto urbano en bici de carga. Sirve de puente entre los vídeos de reparto de esta misma lista y los datos que los respaldan.',
   'claude-opus-5', now(), 69, 'Único apoyo académico del reparto en bici de carga en esta tanda.',
   'vivo', now(), 'agente:prog8'),
  ('AGR_MEL_050', 'web', 'grafica', 'https://www.statista.com/topics/10389/e-bikes-in-europe/', NULL,
   'E-bikes in Europe — estadísticas y hechos',
   'Statista', 'en', NULL,
   'Recopilación cómoda de cifras europeas, útil para orientarse rápido. Es la fuente más débil de las cincuenta: agrega datos de terceros y buena parte está tras muro de pago, así que se cita para ubicarse, no para afirmar.',
   'claude-opus-5', now(), 48, 'La más débil de las 50: agrega datos de terceros y está tras muro de pago.',
   'bloquea_robots', now(), 'agente:prog8')
ON CONFLICT (id) DO NOTHING;

-- ── QUÉ PIEZA VA EN QUÉ SUBTEMA ─────────────────────────────────────────────
-- Con `tipo = 'agregado'`, que es la pareja (tipo, entity_id) que ya usan
-- `publicacion_meta` y las denuncias. Varias piezas están en más de un subtema
-- a propósito: Eugenio decidió en 0120 que una publicación pueda estar en
-- varios, y un estudio sobre patinetes compartidos es a la vez de reparto modal
-- y de patinete compartido.

INSERT INTO subtema_contenido (subtema_id, tipo, entity_id, puesto_por) VALUES
  ('ST_MEL_CARGA', 'agregado', 'AGR_MEL_001', 'agente:prog8'),
  ('ST_MEL_SUST_MODAL', 'agregado', 'AGR_MEL_002', 'agente:prog8'),
  ('ST_MEL_INFRA', 'agregado', 'AGR_MEL_003', 'agente:prog8'),
  ('ST_MEL_BICI', 'agregado', 'AGR_MEL_004', 'agente:prog8'),
  ('ST_MEL_CARGA', 'agregado', 'AGR_MEL_005', 'agente:prog8'),
  ('ST_MEL_CARGA_FAM', 'agregado', 'AGR_MEL_006', 'agente:prog8'),
  ('ST_MEL_SUST_MODAL', 'agregado', 'AGR_MEL_006', 'agente:prog8'),
  ('ST_MEL_MERCADO_EU', 'agregado', 'AGR_MEL_007', 'agente:prog8'),
  ('ST_MEL_MERCADO', 'agregado', 'AGR_MEL_008', 'agente:prog8'),
  ('ST_MEL_BICI_LIGERA', 'agregado', 'AGR_MEL_009', 'agente:prog8'),
  ('ST_MEL_CARGA', 'agregado', 'AGR_MEL_009', 'agente:prog8'),
  ('ST_MEL_CARGA_FAM', 'agregado', 'AGR_MEL_010', 'agente:prog8'),
  ('ST_MEL', 'agregado', 'AGR_MEL_011', 'agente:prog8'),
  ('ST_MEL_BAT_SOLIDO', 'agregado', 'AGR_MEL_012', 'agente:prog8'),
  ('ST_MEL_MERCADO_CN', 'agregado', 'AGR_MEL_013', 'agente:prog8'),
  ('ST_MEL_TRICI', 'agregado', 'AGR_MEL_014', 'agente:prog8'),
  ('ST_MEL_BICI_LIGERA', 'agregado', 'AGR_MEL_015', 'agente:prog8'),
  ('ST_MEL_CICLO', 'agregado', 'AGR_MEL_016', 'agente:prog8'),
  ('ST_MEL_CARGA', 'agregado', 'AGR_MEL_017', 'agente:prog8'),
  ('ST_MEL_CARGA', 'agregado', 'AGR_MEL_018', 'agente:prog8'),
  ('ST_MEL_NORMA_ES', 'agregado', 'AGR_MEL_019', 'agente:prog8'),
  ('ST_MEL_SEG', 'agregado', 'AGR_MEL_020', 'agente:prog8'),
  ('ST_MEL_NORMA_INT', 'agregado', 'AGR_MEL_020', 'agente:prog8'),
  ('ST_MEL_SEG', 'agregado', 'AGR_MEL_021', 'agente:prog8'),
  ('ST_MEL_SEG', 'agregado', 'AGR_MEL_022', 'agente:prog8'),
  ('ST_MEL_INFRA', 'agregado', 'AGR_MEL_022', 'agente:prog8'),
  ('ST_MEL_SEG', 'agregado', 'AGR_MEL_023', 'agente:prog8'),
  ('ST_MEL_SEG', 'agregado', 'AGR_MEL_024', 'agente:prog8'),
  ('ST_MEL_SEG', 'agregado', 'AGR_MEL_025', 'agente:prog8'),
  ('ST_MEL_VMP_COMP', 'agregado', 'AGR_MEL_025', 'agente:prog8'),
  ('ST_MEL_MERCADO_CIF', 'agregado', 'AGR_MEL_026', 'agente:prog8'),
  ('ST_MEL_MERCADO_CIF', 'agregado', 'AGR_MEL_027', 'agente:prog8'),
  ('ST_MEL_NORMA_ES', 'agregado', 'AGR_MEL_028', 'agente:prog8'),
  ('ST_MEL_VMP', 'agregado', 'AGR_MEL_028', 'agente:prog8'),
  ('ST_MEL_NORMA_ES', 'agregado', 'AGR_MEL_029', 'agente:prog8'),
  ('ST_MEL_SUST_MODAL', 'agregado', 'AGR_MEL_030', 'agente:prog8'),
  ('ST_MEL_SUST_MODAL', 'agregado', 'AGR_MEL_031', 'agente:prog8'),
  ('ST_MEL_SUST_MODAL', 'agregado', 'AGR_MEL_032', 'agente:prog8'),
  ('ST_MEL_VMP_COMP', 'agregado', 'AGR_MEL_032', 'agente:prog8'),
  ('ST_MEL_SUST_SALUD', 'agregado', 'AGR_MEL_033', 'agente:prog8'),
  ('ST_MEL_BAT_FUEGO', 'agregado', 'AGR_MEL_034', 'agente:prog8'),
  ('ST_MEL_BAT_CERT', 'agregado', 'AGR_MEL_035', 'agente:prog8'),
  ('ST_MEL_NORMA_US', 'agregado', 'AGR_MEL_036', 'agente:prog8'),
  ('ST_MEL_BAT_CERT', 'agregado', 'AGR_MEL_036', 'agente:prog8'),
  ('ST_MEL_BAT_FUEGO', 'agregado', 'AGR_MEL_037', 'agente:prog8'),
  ('ST_MEL_MERCADO_CIF', 'agregado', 'AGR_MEL_038', 'agente:prog8'),
  ('ST_MEL_DATOS_PANEL', 'agregado', 'AGR_MEL_039', 'agente:prog8'),
  ('ST_MEL_VMP_COMP', 'agregado', 'AGR_MEL_039', 'agente:prog8'),
  ('ST_MEL_DATOS_PANEL', 'agregado', 'AGR_MEL_040', 'agente:prog8'),
  ('ST_MEL_DATOS_GBFS', 'agregado', 'AGR_MEL_041', 'agente:prog8'),
  ('ST_MEL_DATOS_MDS', 'agregado', 'AGR_MEL_042', 'agente:prog8'),
  ('ST_MEL_DATOS_GBFS', 'agregado', 'AGR_MEL_043', 'agente:prog8'),
  ('ST_MEL_DATOS_GBFS', 'agregado', 'AGR_MEL_044', 'agente:prog8'),
  ('ST_MEL_DATOS_MDS', 'agregado', 'AGR_MEL_045', 'agente:prog8'),
  ('ST_MEL_DATOS_PANEL', 'agregado', 'AGR_MEL_045', 'agente:prog8'),
  ('ST_MEL_DATOS_MDS', 'agregado', 'AGR_MEL_046', 'agente:prog8'),
  ('ST_MEL_MERCADO_CIF', 'agregado', 'AGR_MEL_047', 'agente:prog8'),
  ('ST_MEL_INFRA', 'agregado', 'AGR_MEL_048', 'agente:prog8'),
  ('ST_MEL_SUST_MODAL', 'agregado', 'AGR_MEL_048', 'agente:prog8'),
  ('ST_MEL_CARGA_REP', 'agregado', 'AGR_MEL_049', 'agente:prog8'),
  ('ST_MEL_MERCADO_CIF', 'agregado', 'AGR_MEL_050', 'agente:prog8')
ON CONFLICT DO NOTHING;

-- ── LOS HUECOS ──────────────────────────────────────────────────────────────
-- Subtemas que el tema pide y que estas 50 NO llenan. No se crean: se anotan.
-- Un árbol que sabe lo que le falta vale más que uno que lo disimula.
--
--   · Pedaleo sin cadena (transmisión en serie)  (colgaría de ST_MEL_BICI)
--     El ejemplo que puso Eugenio. Ninguna de las 50 lo toca: existe producto real (Schaeffler Free Drive, buses y bicis de accionamiento serie) pero no ha salido en esta primera pasada.
--   · Motor central contra motor de buje  (colgaría de ST_MEL_BICI)
--     Es la primera decisión técnica de cualquier comprador y no hay ni una pieza dedicada.
--   · Robo, marcaje y recuperación  (colgaría de ST_MEL)
--     El motivo número uno por el que la gente no se compra una en España, y cero contenido.
--   · Segunda vida y reciclaje de batería  (colgaría de ST_MEL_BAT)
--     El final de la vida del producto no aparece en ninguna de las 50.
--   · Ayudas y subvenciones en España  (colgaría de ST_MEL_NORMA_ES)
--     Los planes MOVES y las ayudas municipales no están cubiertos.
--   · Aparcamiento seguro y portales  (colgaría de ST_MEL_INFRA)
--     El problema del ascensor y el trastero decide la compra más que la autonomía.
--
-- Ese es el encargo de la siguiente tanda, no un defecto de ésta.
