import { db } from './index.ts';
import * as schema from './schema.ts';
import { sql } from 'drizzle-orm';

const TERRITORY_ID = 'T003'; // España

const OBJECTIVE_IDS = {
  AGUA: 'O001',
  ALIMENTACION: 'O002',
  VIVIENDA: 'O003',
  CONVIVENCIA: 'O005',
  ECOSISTEMAS: 'O006',
} as const;

interface IndicatorSeed {
  id: string;
  name: string;
  unit: string;
  category: keyof typeof OBJECTIVE_IDS;
  weight: number;
  rawValue: string;
  score: number;
  weightedScore: number;
  methodology: string;
  source: string;
  date?: string;
}

const indicators: IndicatorSeed[] = [
  // ===================== AGUA =====================
  {
    id: 'IND_AGUA_ACCESO',
    name: 'Acceso',
    unit: '%',
    category: 'AGUA',
    weight: 0.15,
    rawValue: '84,3% de población con suministro cubierto por el Sistema Nacional de Aguas de Consumo (2024)',
    score: 84.3,
    weightedScore: 12.65,
    methodology: 'Como es un porcentaje de cobertura, puntuación = 84,3.',
    source: 'Ministerio de Sanidad, publicado por INE',
  },
  {
    id: 'IND_AGUA_CALIDAD',
    name: 'Calidad',
    unit: '%',
    category: 'AGUA',
    weight: 0.12,
    rawValue: '61,5% masas superficiales con buen estado ecológico; 86,6% con buen estado químico; 54,2% masas subterráneas con buen estado global; 75,38% estaciones con nitratos <50 mg/l; 76,14% con fosfatos <0,20 mg P-PO₄/l; 96,27% con DBO₅ <10 mg/l',
    score: 72.1,
    weightedScore: 8.65,
    methodology: 'Índice compuesto: 25% ecológico + 20% químico + 20% subterráneas + 15% nitratos + 10% fosfatos + 10% DBO₅.',
    source: 'INE',
  },
  {
    id: 'IND_AGUA_SANEAMIENTO',
    name: 'Saneamiento',
    unit: '%',
    category: 'AGUA',
    weight: 0.12,
    rawValue: '98,37% de la carga contaminante de poblaciones >2.000 hab-eq conectada a colectores conforme a la Directiva 91/271/CEE (2022)',
    score: 98.4,
    weightedScore: 11.80,
    methodology: 'Al ser directamente un porcentaje de cobertura, puntuación = 98,37. Es un buen proxy nacional, aunque no equivale exactamente al indicador universal de saneamiento seguro.',
    source: 'INE',
  },
  {
    id: 'IND_AGUA_DISPONIBILIDAD',
    name: 'Disponibilidad',
    unit: '%',
    category: 'AGUA',
    weight: 0.12,
    rawValue: '73,4% de capacidad de los embalses ocupada, 21/07/2026',
    score: 73.4,
    weightedScore: 8.81,
    methodology: 'Para el MVP, puntuación = nivel de reserva. Es un indicador coyuntural de disponibilidad, no una medida estructural de recursos renovables.',
    source: 'Ministerio de Transición Ecológica',
    date: '2026-07-21',
  },
  {
    id: 'IND_AGUA_ESTRES',
    name: 'Estrés',
    unit: '%',
    category: 'AGUA',
    weight: 0.10,
    rawValue: '19,95% WEI+ (último dato oficial: 2021)',
    score: 50.1,
    weightedScore: 5.01,
    methodology: 'Escala propuesta: 100 puntos con 0% de estrés, 50 puntos con 20% y 0 puntos con 40% o más. España está prácticamente en el umbral del 20%.',
    source: 'INE',
  },
  {
    id: 'IND_AGUA_CONSUMO',
    name: 'Consumo',
    unit: 'l/hab/día',
    category: 'AGUA',
    weight: 0.07,
    rawValue: '128 l/hab/día en hogares (2024)',
    score: 72.0,
    weightedScore: 5.04,
    methodology: 'Escala de eficiencia provisional: ≤100 l/día = 100 puntos; ≥200 = 0; entre ambos, interpolación lineal. 128 → 72 puntos.',
    source: 'INE',
  },
  {
    id: 'IND_AGUA_PERDIDAS',
    name: 'Pérdidas',
    unit: '%',
    category: 'AGUA',
    weight: 0.10,
    rawValue: '14,6% de pérdidas reales en redes (624 hm³ en 2024)',
    score: 77.0,
    weightedScore: 7.70,
    methodology: 'Escala provisional: ≤10% = 100 puntos; ≥30% = 0; interpolación lineal. 14,6% → 77 puntos.',
    source: 'INE',
  },
  {
    id: 'IND_AGUA_REUTILIZACION',
    name: 'Reutilización',
    unit: '%',
    category: 'AGUA',
    weight: 0.07,
    rawValue: '>450 hm³/año, aproximadamente 10% de los caudales utilizados para abastecimiento urbano',
    score: 50.0,
    weightedScore: 3.50,
    methodology: 'Referencia de alto desempeño: 0% = 0 puntos, 20% = 100. 10% → 50 puntos. El dato nacional encontrado es antiguo, por lo que debe sustituirse por una serie actualizada antes de producción.',
    source: 'Ministerio de Transición Ecológica',
  },
  {
    id: 'IND_AGUA_SEQUIA',
    name: 'Sequía',
    unit: '%',
    category: 'AGUA',
    weight: 0.05,
    rawValue: 'Reserva nacional 73,4% a 21/07/2026; MITECO mantiene un sistema específico de indicadores de sequía y escasez por cuenca',
    score: 73.0,
    weightedScore: 3.65,
    methodology: 'Provisional: al no existir un único porcentaje nacional de sequía directamente comparable, se usa la reserva hídrica como proxy temporal. El índice definitivo debería calcularse con los indicadores oficiales de sequía y escasez por sistema de explotación.',
    source: 'Ministerio de Transición Ecológica',
    date: '2026-07-21',
  },

  // ===================== ALIMENTACIÓN =====================
  {
    id: 'IND_ALIMENTACION_ACCESO',
    name: 'Acceso',
    unit: '%',
    category: 'ALIMENTACION',
    weight: 0.17,
    rawValue: '99,8% de la población con acceso físico y económico a alimentos suficientes (2024)',
    score: 99.8,
    weightedScore: 16.97,
    methodology: 'Al ser un porcentaje de cobertura, la puntuación equivale al porcentaje de acceso.',
    source: 'FAO, INE, Ministerio de Agricultura',
  },
  {
    id: 'IND_ALIMENTACION_NUTRICION',
    name: 'Nutrición',
    unit: '%',
    category: 'ALIMENTACION',
    weight: 0.17,
    rawValue: '68% de adultos con alimentación considerada saludable; 36% consume fruta diariamente; 44% verduras diariamente (ENSE 2023)',
    score: 68.0,
    weightedScore: 11.56,
    methodology: 'Índice compuesto basado en calidad nutricional, consumo de frutas y verduras y equilibrio dietético.',
    source: 'ENSE 2023',
  },
  {
    id: 'IND_ALIMENTACION_OBESIDAD',
    name: 'Obesidad',
    unit: '%',
    category: 'ALIMENTACION',
    weight: 0.13,
    rawValue: '16,0% de obesidad en adultos; 37,0% sobrepeso (2023)',
    score: 69.0,
    weightedScore: 8.97,
    methodology: 'Escala: 0% obesidad = 100 puntos; 50% = 0 puntos. España obtiene 69 puntos.',
    source: 'ENSE 2023',
  },
  {
    id: 'IND_ALIMENTACION_SEGURIDAD',
    name: 'Seguridad',
    unit: '%',
    category: 'ALIMENTACION',
    weight: 0.13,
    rawValue: '97,8% de los alimentos cumplen los controles oficiales de seguridad alimentaria (2024)',
    score: 97.8,
    weightedScore: 12.71,
    methodology: 'La puntuación corresponde al porcentaje de cumplimiento de los controles sanitarios.',
    source: 'AESAN',
  },
  {
    id: 'IND_ALIMENTACION_SOSTENIBILIDAD',
    name: 'Sostenibilidad',
    unit: '%',
    category: 'ALIMENTACION',
    weight: 0.10,
    rawValue: '11,8% de la superficie agrícola certificada como ecológica; España es líder de la UE en superficie ecológica (2024)',
    score: 72.0,
    weightedScore: 7.20,
    methodology: 'Índice compuesto entre agricultura ecológica, reducción de emisiones, biodiversidad y prácticas sostenibles.',
    source: 'Ministerio de Agricultura',
  },
  {
    id: 'IND_ALIMENTACION_DESPERDICIO',
    name: 'Desperdicio',
    unit: 'kg/persona/año',
    category: 'ALIMENTACION',
    weight: 0.10,
    rawValue: '30,8 kg de alimentos desperdiciados por persona y año en hogares (2024)',
    score: 69.0,
    weightedScore: 6.90,
    methodology: 'Escala: 0 kg = 100 puntos; 100 kg = 0 puntos. España obtiene 69 puntos.',
    source: 'Ministerio de Agricultura',
  },
  {
    id: 'IND_ALIMENTACION_AUTOSUFICIENCIA',
    name: 'Autosuficiencia',
    unit: '%',
    category: 'ALIMENTACION',
    weight: 0.10,
    rawValue: 'Aproximadamente 66% de autosuficiencia alimentaria; dependencia relevante de cereales, soja y fertilizantes importados (2024)',
    score: 66.0,
    weightedScore: 6.60,
    methodology: 'La puntuación refleja la capacidad del país para abastecer su demanda alimentaria con producción propia.',
    source: 'Ministerio de Agricultura',
  },
  {
    id: 'IND_ALIMENTACION_PRODUCTIVIDAD',
    name: 'Productividad',
    unit: '%',
    category: 'ALIMENTACION',
    weight: 0.10,
    rawValue: 'Predomina una agricultura intensiva y extensiva convencional; la agroforestería sintrópica representa una fracción residual de la superficie agrícola (<0,1%)',
    score: 42.0,
    weightedScore: 4.20,
    methodology: 'Escala basada en el valor generado por hectárea y el nivel de integración ecológica del sistema productivo: 100 = agroforestería sintrópica, 80 = agroforestal diversificada, 60 = horticultura intensiva sostenible, 40 = agricultura convencional, 20 = monocultivos extensivos, 0 = monocultivos altamente degradantes.',
    source: 'Ministerio de Agricultura',
  },

  // ===================== VIVIENDA =====================
  {
    id: 'IND_VIVIENDA_ACCESO',
    name: 'Acceso',
    unit: '%',
    category: 'VIVIENDA',
    weight: 0.17,
    rawValue: '76,1% de los hogares son propietarios de su vivienda; el resto reside principalmente en alquiler (2024)',
    score: 76.1,
    weightedScore: 12.94,
    methodology: 'La puntuación corresponde al porcentaje de hogares con acceso estable a una vivienda principal.',
    source: 'INE',
  },
  {
    id: 'IND_VIVIENDA_ASEQUIBILIDAD',
    name: 'Asequibilidad',
    unit: '%',
    category: 'VIVIENDA',
    weight: 0.17,
    rawValue: 'Los hogares destinan de media el 31% de su renta al coste de la vivienda; en grandes ciudades supera el 40% (2024)',
    score: 52.0,
    weightedScore: 8.84,
    methodology: 'Escala: ≤20% de la renta = 100 puntos; ≥50% = 0 puntos; interpolación lineal.',
    source: 'INE',
  },
  {
    id: 'IND_VIVIENDA_CALIDAD',
    name: 'Calidad',
    unit: '%',
    category: 'VIVIENDA',
    weight: 0.14,
    rawValue: '91% de las viviendas presentan condiciones adecuadas de habitabilidad (humedades, iluminación, espacio y estado estructural) (EU-SILC 2024)',
    score: 91.0,
    weightedScore: 12.74,
    methodology: 'Índice compuesto de calidad constructiva, confort y ausencia de deficiencias graves.',
    source: 'EU-SILC 2024',
  },
  {
    id: 'IND_VIVIENDA_EFICIENCIA',
    name: 'Eficiencia',
    unit: '%',
    category: 'VIVIENDA',
    weight: 0.12,
    rawValue: 'Aproximadamente el 16% del parque residencial dispone de calificación energética A o B; predominan viviendas E y F (2024)',
    score: 45.0,
    weightedScore: 5.40,
    methodology: 'Índice basado en la distribución de certificados energéticos del parque residencial.',
    source: 'Ministerio de Transportes y Agenda Urbana',
  },
  {
    id: 'IND_VIVIENDA_ESPACIO',
    name: 'Espacio',
    unit: 'm²/vivienda',
    category: 'VIVIENDA',
    weight: 0.10,
    rawValue: 'Superficie útil media de 101 m² por vivienda; ocupación media de 2,5 personas por hogar (2024)',
    score: 84.0,
    weightedScore: 8.40,
    methodology: 'Escala basada en m² disponibles por persona y ausencia de hacinamiento.',
    source: 'INE',
  },
  {
    id: 'IND_VIVIENDA_SOSTENIBILIDAD',
    name: 'Sostenibilidad',
    unit: '%',
    category: 'VIVIENDA',
    weight: 0.10,
    rawValue: 'Alrededor del 2% anual de las viviendas incorporan rehabilitación energética significativa; baja tasa de renovación del parque (2024)',
    score: 55.0,
    weightedScore: 5.50,
    methodology: 'Índice compuesto de rehabilitación energética, materiales sostenibles y emisiones operativas.',
    source: 'Ministerio de Transportes y Agenda Urbana',
  },
  {
    id: 'IND_VIVIENDA_ESTABILIDAD',
    name: 'Estabilidad',
    unit: '%',
    category: 'VIVIENDA',
    weight: 0.10,
    rawValue: 'Aproximadamente el 96% de los hogares mantiene una vivienda estable durante todo el año; baja incidencia de desahucios respecto al parque total (2024)',
    score: 96.0,
    weightedScore: 9.60,
    methodology: 'Índice basado en estabilidad residencial, permanencia y riesgo de pérdida de vivienda.',
    source: 'INE',
  },
  {
    id: 'IND_VIVIENDA_PRODUCTIVIDAD',
    name: 'Productividad',
    unit: '%',
    category: 'VIVIENDA',
    weight: 0.10,
    rawValue: 'El parque residencial genera un valor limitado además de la función habitacional: escasa integración de autoconsumo, captación de agua, producción alimentaria, espacios compartidos o usos mixtos (<10% de las viviendas)',
    score: 38.0,
    weightedScore: 3.80,
    methodology: 'Escala: 100 = vivienda regenerativa (energía positiva, agua, alimentos, biodiversidad y usos productivos); 75 = vivienda autosuficiente; 50 = vivienda eficiente; 25 = vivienda convencional; 0 = vivienda altamente dependiente de recursos externos.',
    source: 'Ministerio de Transportes y Agenda Urbana',
  },

  // ===================== CONVIVENCIA =====================
  {
    id: 'IND_CONVIVENCIA_SEGURIDAD',
    name: 'Seguridad',
    unit: 'delitos/1000 hab',
    category: 'CONVIVENCIA',
    weight: 0.18,
    rawValue: '48,8 infracciones penales por 1.000 habitantes (2024)',
    score: 83.0,
    weightedScore: 14.94,
    methodology: 'Escala: ≤20 delitos/1000 = 100; ≥150 = 0. Interpolación.',
    source: 'Ministerio del Interior',
  },
  {
    id: 'IND_CONVIVENCIA_CONFIANZA',
    name: 'Confianza',
    unit: '%',
    category: 'CONVIVENCIA',
    weight: 0.15,
    rawValue: '39% de la población declara confiar en la mayoría de las personas (ESS)',
    score: 58.0,
    weightedScore: 8.70,
    methodology: 'Escala: 70% = 100; 20% = 0. Basado en confianza interpersonal.',
    source: 'European Social Survey (ESS)',
  },
  {
    id: 'IND_CONVIVENCIA_PARTICIPACION',
    name: 'Participación',
    unit: '%',
    category: 'CONVIVENCIA',
    weight: 0.14,
    rawValue: '16% participa regularmente en asociaciones, voluntariado o iniciativas comunitarias',
    score: 55.0,
    weightedScore: 7.70,
    methodology: 'Escala: 30% = 100; 5% = 0. Participación activa en la sociedad civil.',
    source: 'European Social Survey (ESS)',
  },
  {
    id: 'IND_CONVIVENCIA_IGUALDAD',
    name: 'Igualdad',
    unit: 'índice Gini',
    category: 'CONVIVENCIA',
    weight: 0.13,
    rawValue: 'Índice de Gini: 31,5 tras transferencias (2024)',
    score: 68.0,
    weightedScore: 8.84,
    methodology: 'Escala: Gini 20 = 100; Gini 45 = 0. Menor desigualdad implica mayor cohesión.',
    source: 'INE',
  },
  {
    id: 'IND_CONVIVENCIA_INCLUSION',
    name: 'Inclusión',
    unit: '%',
    category: 'CONVIVENCIA',
    weight: 0.13,
    rawValue: '30,5% de población en riesgo de pobreza o exclusión (AROPE, 2024)',
    score: 57.0,
    weightedScore: 7.41,
    methodology: 'Escala: 10% = 100; 50% = 0. Menor exclusión social implica mayor convivencia.',
    source: 'AROPE / INE',
  },
  {
    id: 'IND_CONVIVENCIA_POLARIZACION',
    name: 'Polarización',
    unit: '%',
    category: 'CONVIVENCIA',
    weight: 0.12,
    rawValue: 'Polarización política y social elevada según Eurobarómetro y ESS',
    score: 52.0,
    weightedScore: 6.24,
    methodology: 'Índice compuesto basado en percepción de división social, tolerancia y consenso democrático.',
    source: 'Eurobarómetro / ESS',
  },
  {
    id: 'IND_CONVIVENCIA_DIVERSIDAD',
    name: 'Diversidad',
    unit: '%',
    category: 'CONVIVENCIA',
    weight: 0.08,
    rawValue: '19,3% de residentes nacidos en el extranjero; integración moderadamente alta',
    score: 76.0,
    weightedScore: 6.08,
    methodology: 'Combina diversidad cultural e integración efectiva. Alta diversidad con buena integración obtiene mayor puntuación.',
    source: 'INE',
  },
  {
    id: 'IND_CONVIVENCIA_SOLIDARIDAD',
    name: 'Solidaridad',
    unit: '%',
    category: 'CONVIVENCIA',
    weight: 0.07,
    rawValue: 'Donaciones, voluntariado y ayuda informal por encima de la media europea',
    score: 72.0,
    weightedScore: 5.04,
    methodology: 'Índice compuesto de voluntariado, ayuda vecinal y donaciones.',
    source: 'European Social Survey (ESS)',
  },

  // ===================== ECOSISTEMAS =====================
  {
    id: 'IND_ECOSISTEMAS_BIODIVERSIDAD',
    name: 'Biodiversidad',
    unit: '%',
    category: 'ECOSISTEMAS',
    weight: 0.18,
    rawValue: 'Aproximadamente el 27% de las especies evaluadas presentan algún grado de amenaza; España alberga la mayor biodiversidad de la UE',
    score: 74.0,
    weightedScore: 13.32,
    methodology: 'Índice basado en el estado de conservación de especies. 100 = ecosistemas plenamente conservados.',
    source: 'MITECO',
  },
  {
    id: 'IND_ECOSISTEMAS_PROTECCION',
    name: 'Protección',
    unit: '%',
    category: 'ECOSISTEMAS',
    weight: 0.15,
    rawValue: '36,8% del territorio terrestre y 21% del mar cuentan con alguna figura de protección (2024)',
    score: 89.0,
    weightedScore: 13.35,
    methodology: 'Escala basada en el porcentaje protegido y el grado de protección efectiva.',
    source: 'MITECO',
  },
  {
    id: 'IND_ECOSISTEMAS_BOSQUES',
    name: 'Bosques',
    unit: '%',
    category: 'ECOSISTEMAS',
    weight: 0.14,
    rawValue: 'La superficie forestal ocupa aproximadamente el 56% del territorio; aumenta ligeramente cada año, aunque existen incendios recurrentes',
    score: 78.0,
    weightedScore: 10.92,
    methodology: 'Índice compuesto de superficie forestal, estado de conservación e impacto de incendios.',
    source: 'MITECO',
  },
  {
    id: 'IND_ECOSISTEMAS_AGUA',
    name: 'Agua',
    unit: '%',
    category: 'ECOSISTEMAS',
    weight: 0.14,
    rawValue: 'En torno al 60% de las masas de agua alcanzan un buen estado ecológico y químico',
    score: 60.0,
    weightedScore: 8.40,
    methodology: 'Basado en el porcentaje de masas de agua en buen estado según la Directiva Marco del Agua.',
    source: 'Ministerio de Transición Ecológica',
  },
  {
    id: 'IND_ECOSISTEMAS_EMISIONES',
    name: 'Emisiones',
    unit: 'tCO2e/hab',
    category: 'ECOSISTEMAS',
    weight: 0.12,
    rawValue: 'Emisiones territoriales de ≈5,5 tCO2e por habitante (2024)',
    score: 63.0,
    weightedScore: 7.56,
    methodology: 'Escala: 0 t = 100; 15 t = 0. Refleja la presión climática sobre los ecosistemas.',
    source: 'MITECO',
  },
  {
    id: 'IND_ECOSISTEMAS_REGENERACION',
    name: 'Regeneración',
    unit: '%',
    category: 'ECOSISTEMAS',
    weight: 0.10,
    rawValue: 'La restauración ecológica avanza, pero menos del 5% de los ecosistemas degradados se restauran cada año',
    score: 48.0,
    weightedScore: 4.80,
    methodology: 'Índice basado en restauración de ríos, humedales y bosques degradados.',
    source: 'MITECO',
  },
  {
    id: 'IND_ECOSISTEMAS_CIRCULARIDAD',
    name: 'Circularidad',
    unit: '%',
    category: 'ECOSISTEMAS',
    weight: 0.09,
    rawValue: 'Tasa de uso circular de materiales del ≈8,5%, inferior a la media europea',
    score: 52.0,
    weightedScore: 4.68,
    methodology: 'Índice basado en reutilización de materiales, reciclaje y reducción de extracción de recursos.',
    source: 'Eurostat',
  },
  {
    id: 'IND_ECOSISTEMAS_PRODUCTIVIDAD',
    name: 'Productividad',
    unit: '%',
    category: 'ECOSISTEMAS',
    weight: 0.08,
    rawValue: 'Predominan ecosistemas parcialmente transformados; baja implantación de modelos regenerativos (agricultura regenerativa, agroforestería, renaturalización urbana, restauración de suelos)',
    score: 54.0,
    weightedScore: 4.32,
    methodology: 'Escala: 100 = ecosistemas altamente regenerativos (aumentan biodiversidad, fertilidad y captura de carbono); 0 = ecosistemas severamente degradados.',
    source: 'MITECO',
  },
];

async function seed() {
  console.log('Seeding indicators for España...');

  const ids = indicators.map(i => i.id);
  await db.execute(sql`
    DELETE FROM indicator_observations
    WHERE territory_id = ${TERRITORY_ID} AND indicator_id IN ${ids}
  `);

  for (const ind of indicators) {
    await db.insert(schema.indicators).values({
      id: ind.id,
      name: ind.name,
      unit: ind.unit,
      category: ind.category,
      direction: 'higher_is_better',
      weight: ind.weight,
      methodology: ind.methodology,
      objectiveId: OBJECTIVE_IDS[ind.category],
    }).onConflictDoUpdate({
      target: schema.indicators.id,
      set: {
        name: ind.name,
        unit: ind.unit,
        category: ind.category,
        weight: ind.weight,
        methodology: ind.methodology,
        objectiveId: OBJECTIVE_IDS[ind.category],
      },
    });

    await db.insert(schema.indicatorObservations).values({
      indicatorId: ind.id,
      territoryId: TERRITORY_ID,
      value: ind.score,
      rawValue: ind.rawValue,
      score: ind.score,
      weightedScore: ind.weightedScore,
      date: ind.date,
      source: ind.source,
    }).onConflictDoNothing();
  }

  console.log(`Seeding completed! (${indicators.length} indicators)`);
  process.exit(0);
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
