// ============================================================================
// LOS DIBUJOS DE LOS ICONOS DE TRAZO (D90, 2026-08-21)
// ============================================================================
// El diccionario que decide QUÉ icono le toca a un nombre vive en
// `src/utils/iconoDeNombre.ts`, y no importa nada de aquí: lo usa también el
// servidor al crear un proyecto, y meterle lucide-react sería meter React en
// el backend. Aquí están los DIBUJOS, que solo hacen falta en el navegador.
//
// ── DE 53 A 988 (2026-08-22, hormiguero: «me gustaría que la librería que se
//    permite escoger de iconos sea 10 veces más amplia») ─────────────────────
//
// Eran 53: los que el diccionario automático podía llegar a devolver. Para
// elegir a mano eso es poquísimo — no había ni «barco de vela», ni «guitarra»,
// ni «huella», ni la mitad de las cosas que una persona quiere poner en un
// proyecto suyo.
//
// LA LISTA ESTÁ GENERADA DEL PROPIO PAQUETE, no escrita a mano: se leyeron los
// 5.592 iconos que trae lucide y se quitaron las FAMILIAS que no nombran una
// cosa —flechas, chevrones, alineaciones, cuadrados, gráficas, estados «Off» y
// «Check»—, que son las que hinchan el catálogo sin añadir nada que alguien
// vaya a elegir para su proyecto. Quedan 988, que son objetos, sitios,
// animales, herramientas, comida, transporte, ciencia y oficios.
//
// LO QUE CUESTA, con número: el paquete de la aplicación pasa de 5,87 MB a lo
// que diga la medición de abajo. Traerlos TODOS (los 5.592) serían unos 3 MB
// más para que nadie llegue nunca a mirar la mitad; traerlos bajo demanda
// obligaría a que el menú lateral, las tarjetas y el visor esperasen una
// descarga para pintar un icono ya elegido, que es peor.
import {
  Accessibility, Activity, ActivitySquare, AirVent, Airplay, AlarmClock, AlarmSmoke, Album,
  AlertCircle, AlertOctagon, AlertTriangle, Ambulance, Amphora, Anchor, Angry, Annoyed, Antenna,
  Anvil, Aperture, AppWindow, AppWindowMac, Apple, Archive, ArchiveRestore, AreaChart, Armchair,
  Asterisk, AsteriskSquare, AtSign, Atom, AudioLines, AudioWaveform, Award, Axe, Axis3D, Axis3d,
  Baby, Backpack, BaggageClaim, Ban, Banana, Bandage, Banknote, Bath, Battery, BatteryCharging,
  BatteryFull, BatteryLow, BatteryMedium, BatteryWarning, Beaker, Bean, Bed, BedDouble, BedSingle,
  Beef, Beer, Bell, BellElectric, BellRing, BicepsFlexed, Bike, Binary, Binoculars, Biohazard,
  Bird, Bitcoin, Blend, Blinds, Blocks, Bluetooth, BluetoothConnected, BluetoothSearching, Bolt,
  Bomb, Bone, Book, BookA, BookAudio, BookCopy, BookHeadphones, BookHeart, BookImage, BookKey,
  BookLock, BookMarked, BookOpen, BookOpenText, BookTemplate, BookText, BookType, BookUser,
  Bookmark, BoomBox, Bot, BotMessageSquare, BottleWine, BowArrow, Box, BoxSelect, Boxes, Braces,
  Brackets, Brain, BrainCircuit, BrickWall, BrickWallFire, BrickWallShield, Briefcase,
  BriefcaseBusiness, BriefcaseConveyorBelt, BriefcaseMedical, BringToFront, Brush, BrushCleaning,
  Bubbles, Bug, Building, Building2, Bus, BusFront, Cable, CableCar, Cake, CakeSlice, Calculator,
  Calendar, CalendarClock, CalendarDays, CalendarFold, CalendarHeart, CalendarRange, CalendarSync,
  Camera, CandlestickChart, Candy, CandyCane, Cannabis, Captions, Car, CarFront, CarTaxiFront,
  Caravan, CardSim, Carrot, CassetteTape, Cast, Castle, Cat, Cctv, CheckCircle, CheckLine,
  CheckSquare, ChefHat, Cherry, Chrome, Chromium, Church, Cigarette, CircuitBoard, Citrus,
  Clapperboard, Clipboard, ClipboardClock, ClipboardCopy, ClipboardEdit, ClipboardList,
  ClipboardPaste, ClipboardPenLine, ClipboardSignature, ClipboardType, Clock, ClockFading,
  ClosedCaption, Cloud, CloudDownload, CloudDrizzle, CloudFog, CloudHail, CloudLightning,
  CloudMoon, CloudMoonRain, CloudRain, CloudRainWind, CloudSnow, CloudSun, CloudSunRain,
  CloudUpload, Cloudy, Clover, Club, Code, CodeSquare, CodeXml, Codepen, Codesandbox, Coffee,
  Coins, Combine, Command, Compass, Component, Computer, ConciergeBell, Cone, Construction,
  Contact, ContactRound, Container, Contrast, Cookie, CookingPot, Copy, CopySlash, Copyleft,
  Copyright, Cpu, CreativeCommons, CreditCard, Croissant, Crop, Cross, Crosshair, Crown, Cuboid,
  CupSoda, CurlyBraces, Currency, Cylinder, Dam, Database, DatabaseBackup, DatabaseZap, Delete,
  Dessert, Diameter, Dices, Disc, DiscAlbum, Divide, DivideCircle, DivideSquare, Dna, Dock, Dog,
  DollarSign, Donut, DoorClosed, DoorClosedLocked, DoorOpen, DotSquare, Download, DownloadCloud,
  DraftingCompass, Drama, Dribbble, Drill, Drone, Droplet, Droplets, Drum, Drumstick, Dumbbell,
  Ear, Earth, EarthLock, Eclipse, Edit, Egg, EggFried, Equal, EqualApproximately, EqualNot,
  EqualSquare, Eraser, EthernetPort, Euro, EvCharger, Expand, ExternalLink, Eye, EyeClosed,
  Facebook, Factory, Fan, FastForward, Feather, Fence, FerrisWheel, Figma, File, FileArchive,
  FileAudio, FileAxis3D, FileAxis3d, FileBadge, FileBarChart, FileBox, FileChartColumn,
  FileChartLine, FileChartPie, FileClock, FileCode, FileDiff, FileDigit, FileEdit, FileHeart,
  FileImage, FileInput, FileJson, FileKey, FileLineChart, FileLock, FileMusic, FileOutput,
  FilePenLine, FilePieChart, FileQuestionMark, FileScan, FileSignature, FileSliders,
  FileSpreadsheet, FileStack, FileSymlink, FileTerminal, FileText, FileType, FileUser, FileVideo,
  FileVideoCamera, FileVolume, FileWarning, Files, Film, Filter, Fingerprint, FireExtinguisher,
  Fish, FishSymbol, Flag, Flame, FlameKindling, Flashlight, FlaskConical, FlaskRound, Flower,
  Focus, Footprints, ForkKnife, ForkKnifeCrossed, Forklift, FormInput, Forward, Frame, Framer,
  Frown, Fuel, Fullscreen, FunctionSquare, Funnel, GalleryHorizontal, GalleryHorizontalEnd,
  GalleryThumbnails, GalleryVertical, GalleryVerticalEnd, Gamepad, GanttChart, GanttChartSquare,
  Gauge, GaugeCircle, Gavel, Gem, GeorgianLari, Ghost, Gift, GitBranch, GitCommit,
  GitCommitHorizontal, GitCommitVertical, GitCompare, GitCompareArrows, GitFork, GitGraph,
  GitMerge, GitPullRequest, GitPullRequestArrow, GitPullRequestClosed, GitPullRequestCreate,
  GitPullRequestDraft, Github, Gitlab, GlassWater, Glasses, Globe, Globe2, GlobeLock, Goal, Gpu,
  Grab, GraduationCap, Grape, Grip, GripHorizontal, GripVertical, Guitar, Ham, Hamburger, Hammer,
  Hand, HandCoins, HandFist, HandGrab, HandHeart, HandHelping, HandMetal, HandPlatter, Handbag,
  Handshake, HardDrive, HardDriveDownload, HardDriveUpload, HardHat, Hash, HatGlasses, Haze,
  HdmiPort, Headphones, Headset, Heart, HeartCrack, HeartHandshake, HeartPulse, Heater,
  HelpCircle, HelpingHand, Highlighter, History, Home, Hop, Hospital, Hotel, Hourglass, House,
  HouseHeart, HousePlug, HouseWifi, IceCream, IceCreamBowl, IceCreamCone, IdCard, IdCardLanyard,
  Image, ImageUpscale, Images, Import, Inbox, IndianRupee, Infinity, Info, Inspect,
  InspectionPanel, Instagram, IterationCcw, IterationCw, JapaneseYen, Joystick, Kanban,
  KanbanSquare, Kayak, Key, KeyRound, KeySquare, Keyboard, KeyboardMusic, Lamp, LampCeiling,
  LampDesk, LampFloor, LandPlot, Landmark, Languages, Laptop, LaptopMinimal, Lasso, LassoSelect,
  Laugh, Layers, Layout, LayoutDashboard, LayoutGrid, LayoutList, LayoutPanelTop, LayoutTemplate,
  Leaf, LeafyGreen, Lectern, LetterText, Library, LibrarySquare, LifeBuoy, Ligature, Lightbulb,
  LineChart, LineSquiggle, Link, Linkedin, Locate, LocateFixed, LocationEdit, Lock, LockKeyhole,
  LockKeyholeOpen, LockOpen, LogIn, LogOut, Logs, Lollipop, Luggage, MSquare, Magnet, Mail,
  MailOpen, MailQuestionMark, MailWarning, Mailbox, Mails, Map, MapPin, MapPinCheckInside,
  MapPinHouse, MapPinMinusInside, MapPinPlusInside, MapPinXInside, MapPinned, Mars, MarsStroke,
  Martini, Medal, Megaphone, Meh, MemoryStick, Merge, MessageCircle, MessageCircleCode,
  MessageCircleHeart, MessageCircleMore, MessageCircleReply, MessageCircleWarning, MessageSquare,
  MessageSquareCode, MessageSquareDiff, MessageSquareHeart, MessageSquareLock, MessageSquareMore,
  MessageSquareQuote, MessageSquareReply, MessageSquareShare, MessageSquareText,
  MessageSquareWarning, MessagesSquare, Mic, MicVocal, Microchip, Microscope, Microwave,
  Milestone, Milk, MinusCircle, MinusSquare, Monitor, MonitorCloud, MonitorSmartphone,
  MonitorSpeaker, MonitorStop, Moon, MoonStar, Motorbike, Mountain, MountainSnow, Mouse,
  MousePointer, MousePointerBan, MousePointerClick, Music, Navigation, Network, Newspaper, Nfc,
  NonBinary, Notebook, NotebookTabs, NotebookText, NotepadText, Nut, Omega, Option, Orbit,
  Origami, Outdent, Package, PackageOpen, PaintBucket, PaintRoller, Paintbrush,
  PaintbrushVertical, Palette, Palmtree, Panda, Paperclip, Parentheses, ParkingCircle,
  ParkingMeter, ParkingSquare, PartyPopper, PauseCircle, PauseOctagon, PawPrint, PcCase, PenBox,
  PenLine, PenSquare, PenTool, Pencil, PencilLine, PencilRuler, Pentagon, PercentCircle,
  PercentDiamond, PercentSquare, PersonStanding, PhilippinePeso, Phone, PhoneCall, PhoneForwarded,
  PhoneIncoming, PhoneMissed, PhoneOutgoing, Pi, PiSquare, Piano, Pickaxe, PictureInPicture,
  PiggyBank, Pill, PillBottle, Pin, Pipette, Pizza, Plane, PlaneLanding, PlaneTakeoff, PlayCircle,
  PlaySquare, Plug, PlugZap, PlusCircle, PlusSquare, Pocket, PocketKnife, Podcast, Pointer,
  Popcorn, Popsicle, PoundSterling, Power, PowerCircle, PowerSquare, Presentation, Printer,
  Projector, Proportions, Puzzle, Pyramid, QrCode, Quote, Rabbit, Radar, Radiation, Radical,
  Radio, RadioReceiver, RadioTower, Radius, RailSymbol, Rainbow, Rat, Receipt, ReceiptCent,
  ReceiptEuro, ReceiptIndianRupee, ReceiptJapaneseYen, ReceiptPoundSterling, ReceiptRussianRuble,
  ReceiptSwissFranc, ReceiptText, ReceiptTurkishLira, RectangleCircle, RectangleEllipsis,
  RectangleGoggles, RectangleHorizontal, RectangleVertical, Recycle, RefreshCcw, RefreshCw,
  Refrigerator, RemoveFormatting, Repeat, Replace, ReplaceAll, Reply, ReplyAll, Rewind, Ribbon,
  Rocket, RockingChair, RollerCoaster, Rose, Route, Router, Rss, Ruler, RulerDimensionLine,
  RussianRuble, Sailboat, Salad, Sandwich, Satellite, SatelliteDish, SaudiRiyal, Save, SaveAll,
  Scale, Scale3D, Scale3d, Scan, ScanBarcode, ScanEye, ScanFace, ScanHeart, ScanLine, ScanQrCode,
  ScanText, School, Scissors, ScissorsSquare, ScreenShare, Scroll, ScrollText, SearchCode,
  SearchSlash, Section, Send, SendHorizonal, SendHorizontal, SendToBack, Server, ServerCrash,
  Settings, Shapes, Share, Sheet, Shell, Shield, ShieldBan, ShieldClose, ShieldEllipsis,
  ShieldHalf, ShieldQuestionMark, ShieldUser, Ship, ShipWheel, Shirt, ShoppingBag, ShoppingBasket,
  ShoppingCart, Shovel, ShowerHead, Shredder, Shrimp, Shrink, Shrub, Shuffle, Sidebar,
  SidebarClose, SidebarOpen, Sigma, SigmaSquare, Signal, SignalHigh, SignalLow, SignalMedium,
  SignalZero, Signature, Signpost, Siren, SkipBack, SkipForward, Skull, Slack, Slash, SlashSquare,
  Slice, Sliders, SlidersHorizontal, SlidersVertical, Smartphone, SmartphoneCharging,
  SmartphoneNfc, Smile, Snail, Snowflake, SoapDispenserDroplet, Sofa, SortAsc, SortDesc, Soup,
  Spade, Sparkle, Sparkles, Speaker, Speech, Split, SplitSquareHorizontal, SplitSquareVertical,
  Spool, Spotlight, SprayCan, Sprout, Squircle, Squirrel, Stamp, Star, StarHalf, Stars, StepBack,
  StepForward, Stethoscope, Sticker, StickyNote, StopCircle, Store, Subtitles, Sun, SunDim,
  SunMedium, SunMoon, SunSnow, Sunrise, Sunset, SwatchBook, SwissFranc, SwitchCamera, Sword,
  Swords, Syringe, Table, TableCellsMerge, TableCellsSplit, TableColumnsSplit, TableConfig,
  TableOfContents, TableProperties, TableRowsSplit, Tablet, TabletSmartphone, Tablets, Tag, Tags,
  Tangent, Target, Telescope, Tent, TentTree, Terminal, TerminalSquare, TestTube,
  TestTubeDiagonal, TestTubes, Theater, Thermometer, ThermometerSnowflake, ThermometerSun, Ticket,
  TicketSlash, Tickets, TicketsPlane, Timer, TimerReset, Toilet, ToolCase, Tornado, Torus,
  Touchpad, TowerControl, ToyBrick, Tractor, TrafficCone, Train, TrainFront, TrainFrontTunnel,
  TrainTrack, TramFront, Transgender, Trash, TreeDeciduous, TreePalm, TreePine, Trees, Trello,
  Trophy, Truck, TruckElectric, TurkishLira, Turntable, Turtle, Tv, TvMinimal, Twitch, Twitter,
  Umbrella, University, Unlink, Unlock, UnlockKeyhole, Unplug, Upload, UploadCloud, Usb, User,
  UserCircle, UserLock, UserRound, UserSquare, UserStar, Users, UsersRound, Utensils,
  UtensilsCrossed, UtilityPole, Variable, Vault, VectorSquare, Vegan, VenetianMask, Venus,
  VenusAndMars, Verified, Vibrate, Video, Videotape, View, Voicemail, Volleyball, Volume, Vote,
  Wallet, WalletCards, WalletMinimal, Wallpaper, Wand, WandSparkles, Warehouse, WashingMachine,
  Watch, Waves, WavesLadder, Waypoints, Webcam, Webhook, Weight, Wheat, Wifi, WifiHigh, WifiLow,
  WifiSync, WifiZero, Wind, Wine, Workflow, Worm, Wrench, XCircle, XOctagon, XSquare, Youtube,
  Zap, ZoomIn, ZoomOut,
  type LucideIcon,
} from 'lucide-react';
import { PREFIJO, ICONO_GENERICO } from '../../utils/iconoDeNombre';

/** Todos los que se pueden pintar. Es también la lista que se puede ELEGIR:
 *  que sean la misma es lo que impide que alguien escoja uno que luego no se
 *  dibuja. */
export const ICONOS: Record<string, LucideIcon> = {
  Accessibility, Activity, ActivitySquare, AirVent, Airplay, AlarmClock, AlarmSmoke, Album,
  AlertCircle, AlertOctagon, AlertTriangle, Ambulance, Amphora, Anchor, Angry, Annoyed, Antenna,
  Anvil, Aperture, AppWindow, AppWindowMac, Apple, Archive, ArchiveRestore, AreaChart, Armchair,
  Asterisk, AsteriskSquare, AtSign, Atom, AudioLines, AudioWaveform, Award, Axe, Axis3D, Axis3d,
  Baby, Backpack, BaggageClaim, Ban, Banana, Bandage, Banknote, Bath, Battery, BatteryCharging,
  BatteryFull, BatteryLow, BatteryMedium, BatteryWarning, Beaker, Bean, Bed, BedDouble, BedSingle,
  Beef, Beer, Bell, BellElectric, BellRing, BicepsFlexed, Bike, Binary, Binoculars, Biohazard,
  Bird, Bitcoin, Blend, Blinds, Blocks, Bluetooth, BluetoothConnected, BluetoothSearching, Bolt,
  Bomb, Bone, Book, BookA, BookAudio, BookCopy, BookHeadphones, BookHeart, BookImage, BookKey,
  BookLock, BookMarked, BookOpen, BookOpenText, BookTemplate, BookText, BookType, BookUser,
  Bookmark, BoomBox, Bot, BotMessageSquare, BottleWine, BowArrow, Box, BoxSelect, Boxes, Braces,
  Brackets, Brain, BrainCircuit, BrickWall, BrickWallFire, BrickWallShield, Briefcase,
  BriefcaseBusiness, BriefcaseConveyorBelt, BriefcaseMedical, BringToFront, Brush, BrushCleaning,
  Bubbles, Bug, Building, Building2, Bus, BusFront, Cable, CableCar, Cake, CakeSlice, Calculator,
  Calendar, CalendarClock, CalendarDays, CalendarFold, CalendarHeart, CalendarRange, CalendarSync,
  Camera, CandlestickChart, Candy, CandyCane, Cannabis, Captions, Car, CarFront, CarTaxiFront,
  Caravan, CardSim, Carrot, CassetteTape, Cast, Castle, Cat, Cctv, CheckCircle, CheckLine,
  CheckSquare, ChefHat, Cherry, Chrome, Chromium, Church, Cigarette, CircuitBoard, Citrus,
  Clapperboard, Clipboard, ClipboardClock, ClipboardCopy, ClipboardEdit, ClipboardList,
  ClipboardPaste, ClipboardPenLine, ClipboardSignature, ClipboardType, Clock, ClockFading,
  ClosedCaption, Cloud, CloudDownload, CloudDrizzle, CloudFog, CloudHail, CloudLightning,
  CloudMoon, CloudMoonRain, CloudRain, CloudRainWind, CloudSnow, CloudSun, CloudSunRain,
  CloudUpload, Cloudy, Clover, Club, Code, CodeSquare, CodeXml, Codepen, Codesandbox, Coffee,
  Coins, Combine, Command, Compass, Component, Computer, ConciergeBell, Cone, Construction,
  Contact, ContactRound, Container, Contrast, Cookie, CookingPot, Copy, CopySlash, Copyleft,
  Copyright, Cpu, CreativeCommons, CreditCard, Croissant, Crop, Cross, Crosshair, Crown, Cuboid,
  CupSoda, CurlyBraces, Currency, Cylinder, Dam, Database, DatabaseBackup, DatabaseZap, Delete,
  Dessert, Diameter, Dices, Disc, DiscAlbum, Divide, DivideCircle, DivideSquare, Dna, Dock, Dog,
  DollarSign, Donut, DoorClosed, DoorClosedLocked, DoorOpen, DotSquare, Download, DownloadCloud,
  DraftingCompass, Drama, Dribbble, Drill, Drone, Droplet, Droplets, Drum, Drumstick, Dumbbell,
  Ear, Earth, EarthLock, Eclipse, Edit, Egg, EggFried, Equal, EqualApproximately, EqualNot,
  EqualSquare, Eraser, EthernetPort, Euro, EvCharger, Expand, ExternalLink, Eye, EyeClosed,
  Facebook, Factory, Fan, FastForward, Feather, Fence, FerrisWheel, Figma, File, FileArchive,
  FileAudio, FileAxis3D, FileAxis3d, FileBadge, FileBarChart, FileBox, FileChartColumn,
  FileChartLine, FileChartPie, FileClock, FileCode, FileDiff, FileDigit, FileEdit, FileHeart,
  FileImage, FileInput, FileJson, FileKey, FileLineChart, FileLock, FileMusic, FileOutput,
  FilePenLine, FilePieChart, FileQuestionMark, FileScan, FileSignature, FileSliders,
  FileSpreadsheet, FileStack, FileSymlink, FileTerminal, FileText, FileType, FileUser, FileVideo,
  FileVideoCamera, FileVolume, FileWarning, Files, Film, Filter, Fingerprint, FireExtinguisher,
  Fish, FishSymbol, Flag, Flame, FlameKindling, Flashlight, FlaskConical, FlaskRound, Flower,
  Focus, Footprints, ForkKnife, ForkKnifeCrossed, Forklift, FormInput, Forward, Frame, Framer,
  Frown, Fuel, Fullscreen, FunctionSquare, Funnel, GalleryHorizontal, GalleryHorizontalEnd,
  GalleryThumbnails, GalleryVertical, GalleryVerticalEnd, Gamepad, GanttChart, GanttChartSquare,
  Gauge, GaugeCircle, Gavel, Gem, GeorgianLari, Ghost, Gift, GitBranch, GitCommit,
  GitCommitHorizontal, GitCommitVertical, GitCompare, GitCompareArrows, GitFork, GitGraph,
  GitMerge, GitPullRequest, GitPullRequestArrow, GitPullRequestClosed, GitPullRequestCreate,
  GitPullRequestDraft, Github, Gitlab, GlassWater, Glasses, Globe, Globe2, GlobeLock, Goal, Gpu,
  Grab, GraduationCap, Grape, Grip, GripHorizontal, GripVertical, Guitar, Ham, Hamburger, Hammer,
  Hand, HandCoins, HandFist, HandGrab, HandHeart, HandHelping, HandMetal, HandPlatter, Handbag,
  Handshake, HardDrive, HardDriveDownload, HardDriveUpload, HardHat, Hash, HatGlasses, Haze,
  HdmiPort, Headphones, Headset, Heart, HeartCrack, HeartHandshake, HeartPulse, Heater,
  HelpCircle, HelpingHand, Highlighter, History, Home, Hop, Hospital, Hotel, Hourglass, House,
  HouseHeart, HousePlug, HouseWifi, IceCream, IceCreamBowl, IceCreamCone, IdCard, IdCardLanyard,
  Image, ImageUpscale, Images, Import, Inbox, IndianRupee, Infinity, Info, Inspect,
  InspectionPanel, Instagram, IterationCcw, IterationCw, JapaneseYen, Joystick, Kanban,
  KanbanSquare, Kayak, Key, KeyRound, KeySquare, Keyboard, KeyboardMusic, Lamp, LampCeiling,
  LampDesk, LampFloor, LandPlot, Landmark, Languages, Laptop, LaptopMinimal, Lasso, LassoSelect,
  Laugh, Layers, Layout, LayoutDashboard, LayoutGrid, LayoutList, LayoutPanelTop, LayoutTemplate,
  Leaf, LeafyGreen, Lectern, LetterText, Library, LibrarySquare, LifeBuoy, Ligature, Lightbulb,
  LineChart, LineSquiggle, Link, Linkedin, Locate, LocateFixed, LocationEdit, Lock, LockKeyhole,
  LockKeyholeOpen, LockOpen, LogIn, LogOut, Logs, Lollipop, Luggage, MSquare, Magnet, Mail,
  MailOpen, MailQuestionMark, MailWarning, Mailbox, Mails, Map, MapPin, MapPinCheckInside,
  MapPinHouse, MapPinMinusInside, MapPinPlusInside, MapPinXInside, MapPinned, Mars, MarsStroke,
  Martini, Medal, Megaphone, Meh, MemoryStick, Merge, MessageCircle, MessageCircleCode,
  MessageCircleHeart, MessageCircleMore, MessageCircleReply, MessageCircleWarning, MessageSquare,
  MessageSquareCode, MessageSquareDiff, MessageSquareHeart, MessageSquareLock, MessageSquareMore,
  MessageSquareQuote, MessageSquareReply, MessageSquareShare, MessageSquareText,
  MessageSquareWarning, MessagesSquare, Mic, MicVocal, Microchip, Microscope, Microwave,
  Milestone, Milk, MinusCircle, MinusSquare, Monitor, MonitorCloud, MonitorSmartphone,
  MonitorSpeaker, MonitorStop, Moon, MoonStar, Motorbike, Mountain, MountainSnow, Mouse,
  MousePointer, MousePointerBan, MousePointerClick, Music, Navigation, Network, Newspaper, Nfc,
  NonBinary, Notebook, NotebookTabs, NotebookText, NotepadText, Nut, Omega, Option, Orbit,
  Origami, Outdent, Package, PackageOpen, PaintBucket, PaintRoller, Paintbrush,
  PaintbrushVertical, Palette, Palmtree, Panda, Paperclip, Parentheses, ParkingCircle,
  ParkingMeter, ParkingSquare, PartyPopper, PauseCircle, PauseOctagon, PawPrint, PcCase, PenBox,
  PenLine, PenSquare, PenTool, Pencil, PencilLine, PencilRuler, Pentagon, PercentCircle,
  PercentDiamond, PercentSquare, PersonStanding, PhilippinePeso, Phone, PhoneCall, PhoneForwarded,
  PhoneIncoming, PhoneMissed, PhoneOutgoing, Pi, PiSquare, Piano, Pickaxe, PictureInPicture,
  PiggyBank, Pill, PillBottle, Pin, Pipette, Pizza, Plane, PlaneLanding, PlaneTakeoff, PlayCircle,
  PlaySquare, Plug, PlugZap, PlusCircle, PlusSquare, Pocket, PocketKnife, Podcast, Pointer,
  Popcorn, Popsicle, PoundSterling, Power, PowerCircle, PowerSquare, Presentation, Printer,
  Projector, Proportions, Puzzle, Pyramid, QrCode, Quote, Rabbit, Radar, Radiation, Radical,
  Radio, RadioReceiver, RadioTower, Radius, RailSymbol, Rainbow, Rat, Receipt, ReceiptCent,
  ReceiptEuro, ReceiptIndianRupee, ReceiptJapaneseYen, ReceiptPoundSterling, ReceiptRussianRuble,
  ReceiptSwissFranc, ReceiptText, ReceiptTurkishLira, RectangleCircle, RectangleEllipsis,
  RectangleGoggles, RectangleHorizontal, RectangleVertical, Recycle, RefreshCcw, RefreshCw,
  Refrigerator, RemoveFormatting, Repeat, Replace, ReplaceAll, Reply, ReplyAll, Rewind, Ribbon,
  Rocket, RockingChair, RollerCoaster, Rose, Route, Router, Rss, Ruler, RulerDimensionLine,
  RussianRuble, Sailboat, Salad, Sandwich, Satellite, SatelliteDish, SaudiRiyal, Save, SaveAll,
  Scale, Scale3D, Scale3d, Scan, ScanBarcode, ScanEye, ScanFace, ScanHeart, ScanLine, ScanQrCode,
  ScanText, School, Scissors, ScissorsSquare, ScreenShare, Scroll, ScrollText, SearchCode,
  SearchSlash, Section, Send, SendHorizonal, SendHorizontal, SendToBack, Server, ServerCrash,
  Settings, Shapes, Share, Sheet, Shell, Shield, ShieldBan, ShieldClose, ShieldEllipsis,
  ShieldHalf, ShieldQuestionMark, ShieldUser, Ship, ShipWheel, Shirt, ShoppingBag, ShoppingBasket,
  ShoppingCart, Shovel, ShowerHead, Shredder, Shrimp, Shrink, Shrub, Shuffle, Sidebar,
  SidebarClose, SidebarOpen, Sigma, SigmaSquare, Signal, SignalHigh, SignalLow, SignalMedium,
  SignalZero, Signature, Signpost, Siren, SkipBack, SkipForward, Skull, Slack, Slash, SlashSquare,
  Slice, Sliders, SlidersHorizontal, SlidersVertical, Smartphone, SmartphoneCharging,
  SmartphoneNfc, Smile, Snail, Snowflake, SoapDispenserDroplet, Sofa, SortAsc, SortDesc, Soup,
  Spade, Sparkle, Sparkles, Speaker, Speech, Split, SplitSquareHorizontal, SplitSquareVertical,
  Spool, Spotlight, SprayCan, Sprout, Squircle, Squirrel, Stamp, Star, StarHalf, Stars, StepBack,
  StepForward, Stethoscope, Sticker, StickyNote, StopCircle, Store, Subtitles, Sun, SunDim,
  SunMedium, SunMoon, SunSnow, Sunrise, Sunset, SwatchBook, SwissFranc, SwitchCamera, Sword,
  Swords, Syringe, Table, TableCellsMerge, TableCellsSplit, TableColumnsSplit, TableConfig,
  TableOfContents, TableProperties, TableRowsSplit, Tablet, TabletSmartphone, Tablets, Tag, Tags,
  Tangent, Target, Telescope, Tent, TentTree, Terminal, TerminalSquare, TestTube,
  TestTubeDiagonal, TestTubes, Theater, Thermometer, ThermometerSnowflake, ThermometerSun, Ticket,
  TicketSlash, Tickets, TicketsPlane, Timer, TimerReset, Toilet, ToolCase, Tornado, Torus,
  Touchpad, TowerControl, ToyBrick, Tractor, TrafficCone, Train, TrainFront, TrainFrontTunnel,
  TrainTrack, TramFront, Transgender, Trash, TreeDeciduous, TreePalm, TreePine, Trees, Trello,
  Trophy, Truck, TruckElectric, TurkishLira, Turntable, Turtle, Tv, TvMinimal, Twitch, Twitter,
  Umbrella, University, Unlink, Unlock, UnlockKeyhole, Unplug, Upload, UploadCloud, Usb, User,
  UserCircle, UserLock, UserRound, UserSquare, UserStar, Users, UsersRound, Utensils,
  UtensilsCrossed, UtilityPole, Variable, Vault, VectorSquare, Vegan, VenetianMask, Venus,
  VenusAndMars, Verified, Vibrate, Video, Videotape, View, Voicemail, Volleyball, Volume, Vote,
  Wallet, WalletCards, WalletMinimal, Wallpaper, Wand, WandSparkles, Warehouse, WashingMachine,
  Watch, Waves, WavesLadder, Waypoints, Webcam, Webhook, Weight, Wheat, Wifi, WifiHigh, WifiLow,
  WifiSync, WifiZero, Wind, Wine, Workflow, Worm, Wrench, XCircle, XOctagon, XSquare, Youtube,
  Zap, ZoomIn, ZoomOut,
};

/** El dibujo de un valor «lucide:Truck». Si el nombre no está en la lista
 *  —porque alguien lo escribió a mano, o porque se quitó de aquí— se devuelve
 *  el genérico en vez de nada: un hueco vacío no dice qué ha pasado. */
export const componenteDeTrazo = (icono: string): LucideIcon =>
  ICONOS[icono.slice(PREFIJO.length)] || ICONOS[ICONO_GENERICO];
